### ISSUE TITLE
Test for mean-vol relationship in BC shock

### ISSUE THREAD

**Issue by matdehaven** [VFCI/vfciBusinessCycles#36]
We have identified a set of business cycle shocks.

Can these generate the same mean-volatility relationship that we see present in the gdp-at-risk data?

Previous work from Fernando et al. shows that financial variables can generate both the mean and the volatility, but that purely macro variables cannot.  This can hopefully help us distinguish between our Unemp identified BC shock and the VFCI identified BC shock.

**Comment by matdehaven** [comment]
This is finished with pull request #39.

Fernando, see the mean-vol report: [https://github.com/VFCI/vfciBusinessCycles/blob/main/reports/MeanVolRelationship.pdf](https://github.com/VFCI/vfciBusinessCycles/blob/main/reports/MeanVolRelationship.pdf)

There are four sections:
1. Show Mean-Vol and Mean-Var for 11 variable VAR
2. Same for 10 variable VAR
3. Same for 11 variable VAR estimated in differences for non stationary variables
4. Mean-Vol and Mean-Var for business cycle shock (null result as expected)

My takeaways:
- The mean-vol relationship looks great for unemployment
  - and for the interest rate and surprisingly, for inflation
- It doesn't look great for output, even when I estimate the VAR in differences
- No difference between the VAR with 10 vs. 11 variables (i.e. with and without vfci)

I will likely show the unemployment picture for the presentation to argue our story, but I'm unsure how to answer "why not use output?".

**Comment by fernando-duarte** [comment]
Thanks for all the results! 

- In the very first set of mean-vol plots (page 5, numbered (4)):

   - Eyeballing the slope for the output plot, it seems close to -1. If that is indeed the case, that is the magnitude we would expect and economically significant in that mean-vol move one-for-one. Where you also thinking about the t-stat for the slope coefficient? The significance of the slope coefficient in these plots is of interest, but of more interest is that the coefficients in the VAR are significant. E.g, imagine the coefficient on the VFCI is tiny and insignificant in the vol equation but equal to 1 in the mean equation. Then the slope of the mean-vol line will be large and statistically likely significant. But economically, the VFCI is not really doing anything to the vol, so the mean-vol relation is not meaningful.

   - Another reason to not focus so much on the t-stat of the slope coefficient of the mean-vol line is that the regressors are generated regressors (fitted values) so one would also have to account for that in the standard errors.

   - The R^2 of the same output mean-vol plot, again by eyeballing, does look larger than what we have usually found in other papers (with a smaller VAR). So it may just be the other variables of the VAR, which then means that's just the result we get. Unemployment may be picking up the effect of financial variables better/earlier than output, not so different from the business cycle shock where targeting GDP works but not as well as targeting unemployment.

   - Alternatively, thinking about the mean-vol plot of output together with the mean-vol plot of inflation, it may be the GDP deflator vs PCE that makes a big difference. Based on our talk earlier, worth trying PCE or core PCE.

   - Conceptually, what we want to show is that conditional on the VFCI, mean-vol have the negative relationship. I.e., when the VFCI changes, the economy moves along the mean-vol line, keeping everything else fixed. When shocks hit the economy (when the "everything" that was being kept fixed is allowed to move) conceptually that should make the mean-vol line shift up and down (the intercept changes). Right now, we are using the fitted value for the mean and the vol using all regressors. So we may be looking at the mean-vol conditional on everything, not just conditional on VFCI (not keeping anything fixed). We can think more about this, the immediate idea is to use the fitted values obtained when keeping all regressors at their mean, except the VFCI, where we use the actual values of the VFCI. 

   - A crude way to get the slope of the mean-vol plot while keeping everything fixed except for the VFCI is to divide the estimated coefficient on the VFCI in the equation for the mean by the estimated coefficient on the VFCI in the equation for the vol.
   - Or perhaps we should construct the vol using only VFCI as a regressor rather than all variables of the VAR. 

   - The reason to include all of the VAR variables in the vol regression is to be able to identify the VFCI shock when the VFCI is constructed internally in a manner consistent with the VAR. When the VFCI is external, what regression we run for the vol, or what variables we keep at their mean and which ones we allow to vary depends on what we want to keep fixed, what the meaning of ceteris paribus is for this exercise, and what is allowed to respond to financial conditions endogenously. That's more a question about how to interpret the line we plot.

- Pretty interesting that we do get the null result for the business cycle shock, that supports the story of the endogenous heteroskedasticity (agains the alternative of heteroskedasticity in the structural shocks).

- To respond to "why not use output?", if it is true that the slope is close to -1, then we can use output no problem. The fit is not as tight, but as long as the coefficients on the VFCI on the mean and vol equations are both significant and of opposite signs, the slope of the mean-vol line is, econometrically, already a meaningful object.
